name: builder

on:
  push

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: build client jar
        run: gradle :client:fatJar
      - name: build server jar
        run: gradle :server:fatJar
      - name: deploy client jar to helios
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./client/build/libs/client-1.0-app.jar"
          target: "/home/studs/s408536/prog/lab8/"
      - name: deploy server jar to helios
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./server/build/libs/server-1.0-app.jar"
          target: "/home/studs/s408536/prog/lab8/"
